// pages/api/generate-checklist.ts
// Generate personalized document checklist based on user answers
import { NextApiRequest, NextApiResponse } from 'next'
import OpenAI from 'openai'

const openaiKey = process.env.OPENAI_API_KEY
const client = openaiKey ? new OpenAI({ apiKey: openaiKey }) : null

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  
  const { schemeType, category, isStudent, income } = req.body

  try {
    let checklist = ''

    if (client) {
      // Use AI to generate personalized checklist
      const prompt = `Create a comprehensive, personalized document checklist for a government scheme application.

Scheme Type: ${schemeType || 'General'}
Category: ${category || 'General'}
Is Student: ${isStudent ? 'Yes' : 'No'}
Annual Income: ${income || 'Not specified'}

The checklist should:
1. List all required documents clearly with checkboxes (☐)
2. Be organized by document type (Identity, Income, Category, Educational, etc.)
3. Include helpful notes about where to obtain each document
4. Be in English (clear and simple)
5. Include tips and reminders
6. Be comprehensive but practical

Format as a clear, actionable checklist that the user can print or save.`

      const reply = await client.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          {
            role: 'system',
            content: 'You are a helpful assistant that creates document checklists for government scheme applications. Always provide clear, actionable, and comprehensive checklists.'
          },
          { role: 'user', content: prompt }
        ],
        max_tokens: 800,
        temperature: 0.7
      })

      checklist = reply.choices?.[0]?.message?.content || ''
    }

    // Fallback if AI is not available
    if (!checklist) {
      const docs: string[] = []
      
      // Base documents
      docs.push('☐ Aadhar Card');
      docs.push('☐ PAN Card (if applicable)');
      docs.push('☐ Bank Passbook/Cancelled Cheque');
      docs.push('☐ Passport Size Photographs (2-4 copies)');
      
      // Category-specific
      if (category && category !== 'General' && category !== 'Not Sure') {
        docs.push(`☐ ${category} Category Certificate`);
      }
      
      // Income-related
      if (income && !income.includes('Above ₹10')) {
        docs.push('☐ Income Certificate');
      }
      
      // Scheme-specific
      if (schemeType === 'Scholarship' || isStudent) {
        docs.push('☐ Educational Certificates (10th/12th/Graduation)');
        docs.push('☐ Marksheets (Last 2-3 years)');
        docs.push('☐ Admission Proof (if applicable)');
        docs.push('☐ Fee Receipt (if applicable)');
      }
      
      if (schemeType === 'Disability Benefits') {
        docs.push('☐ Disability Certificate (40% or above)');
        docs.push('☐ Medical Reports');
      }
      
      if (schemeType === 'Women Empowerment') {
        docs.push('☐ Gender Proof (Aadhar/Birth Certificate)');
      }
      
      if (schemeType === 'Farmer Scheme') {
        docs.push('☐ Land Ownership Documents');
        docs.push('☐ Farmer ID Card (if available)');
      }
      
      if (schemeType === 'MSME/Business') {
        docs.push('☐ Business Registration Certificate');
        docs.push('☐ GST Certificate (if applicable)');
        docs.push('☐ Business Address Proof');
      }

      checklist = `📋 PERSONALIZED DOCUMENT CHECKLIST

Generated on: ${new Date().toLocaleDateString('en-IN')}

Scheme Type: ${schemeType || 'Not specified'}
Category: ${category || 'Not specified'}
Student: ${isStudent ? 'Yes' : 'No'}
Income: ${income || 'Not specified'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REQUIRED DOCUMENTS:

${docs.join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 NOTES:
• All documents should be self-attested copies
• Keep original documents ready for verification
• Ensure all documents are recent (not older than 6 months)
• Check specific scheme requirements on official portal

✅ TIP: Use YojanaMitra's auto-fill feature to fill application forms automatically!

Generated by YojanaMitra - Your AI Copilot for Government Schemes`
    }

    return res.status(200).json({
      success: true,
      checklist
    })

  } catch (err: any) {
    console.error('[generate-checklist] Error:', err)
    return res.status(500).json({
      error: err.message || 'Failed to generate checklist',
      details: process.env.NODE_ENV === 'development' ? err.stack : undefined
    })
  }
}


