// pages/api/send-kit-whatsapp.ts
import { NextApiRequest, NextApiResponse } from 'next'
import { sendMessage } from '../../lib/twilioSend'
import fs from 'fs'
import path from 'path'
import archiver from 'archiver'

const YOUR_WHATSAPP_NUMBER = '+917819849984' // Your WhatsApp number

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  
  const { files, schemeTitle, userName, filledPdfUrl, generatedDocs } = req.body

  if (!files || !Array.isArray(files) || files.length === 0) {
    return res.status(400).json({ error: 'Files are required' })
  }

  try {
    // Validate all files exist
    const filePaths: Array<{ path: string; name: string }> = []
    for (const fileInfo of files) {
      const filePath = path.join(process.cwd(), 'public', fileInfo.url.replace(/^\//, ''))
      if (fs.existsSync(filePath)) {
        filePaths.push({
          path: filePath,
          name: fileInfo.name || path.basename(fileInfo.url)
        })
      }
    }

    if (filePaths.length === 0) {
      return res.status(404).json({ error: 'No valid files found' })
    }

    // Create kit ZIP file
    const kitName = schemeTitle 
      ? `${schemeTitle.replace(/[^a-z0-9]/gi, '_')}_ApplicationKit.zip`
      : userName
        ? `${userName.replace(/[^a-z0-9]/gi, '_')}_ApplicationKit.zip`
        : 'application-kit.zip'

    const kitPath = path.join(process.cwd(), 'public', 'kits', kitName)
    const kitsDir = path.join(process.cwd(), 'public', 'kits')
    
    // Ensure kits directory exists
    if (!fs.existsSync(kitsDir)) {
      fs.mkdirSync(kitsDir, { recursive: true })
    }

    // Create zip archive
    const archive = archiver('zip', { zlib: { level: 9 } })
    const output = fs.createWriteStream(kitPath)
    
    archive.pipe(output)

    // Add all files to archive
    for (const { path: filePath, name } of filePaths) {
      archive.file(filePath, { name })
    }

    // Create README
    const readmeContent = `Application Kit for ${schemeTitle || 'Government Scheme'}

Generated on: ${new Date().toLocaleString('en-IN')}
Applicant: ${userName || 'Not specified'}

This kit contains:
${filePaths.map((f, i) => `${i + 1}. ${f.name}`).join('\n')}

Instructions:
1. Review all documents carefully
2. Sign where required
3. Attach any missing documents mentioned in the checklist
4. Submit the application as per the scheme guidelines

For support, contact the scheme helpline or visit the official website.

---
Generated by YojanaMitra - Your AI Copilot for Government Schemes
`

    archive.append(readmeContent, { name: 'README.txt' })
    await archive.finalize()

    // Wait for file to be written
    await new Promise<void>((resolve, reject) => {
      output.on('close', () => resolve())
      output.on('error', reject)
    })

    // Get the public URL for the kit
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || req.headers.origin || 'http://localhost:3000'
    const kitUrl = `${baseUrl}/kits/${kitName}`

    // Build WhatsApp message
    const escapeWhatsApp = (text: string) => text.replace(/[*_~`]/g, '')
    
    const message = `Namaste! 👋

📦 *Application Kit Ready!*

Your complete application kit for *${escapeWhatsApp(schemeTitle || 'Government Scheme')}* is ready!

📋 *Kit Contains:*
${filePaths.map((f, i) => `${i + 1}. ${f.name}`).join('\n')}

📥 *Download Link:*
${kitUrl}

💡 *Instructions:*
1. Download the kit (link provided above)
2. Review all documents
3. Add required signatures
4. Attach any missing documents
5. Submit on the official portal

⚠️ *Important:*
• Submit before the deadline
• Note down your application number
• Check for confirmation

Thank you! 🙏
*YojanaMitra Team*`

    // Check Twilio configuration first
    const accountSid = process.env.TWILIO_ACCOUNT_SID
    const authToken = process.env.TWILIO_AUTH_TOKEN
    const fromNumber = process.env.TWILIO_FROM_NUMBER

    if (!accountSid || !authToken || !fromNumber || 
        accountSid === 'your_twilio_account_sid' || 
        authToken === 'your_twilio_auth_token') {
      console.error('[send-kit-whatsapp] Twilio not configured')
      return res.status(400).json({ 
        error: 'Twilio is not configured. Please set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, and TWILIO_FROM_NUMBER in .env.local',
        hint: 'See TWILIO_SETUP.md for instructions',
        kitUrl // Still return the URL so user can download manually
      })
    }

    // Send via WhatsApp
    const formattedTo = `whatsapp:${YOUR_WHATSAPP_NUMBER}`
    console.log('[send-kit-whatsapp] Sending kit to:', formattedTo)
    console.log('[send-kit-whatsapp] Twilio config check:', {
      hasAccountSid: !!accountSid,
      hasAuthToken: !!authToken,
      fromNumber
    })
    
    const result = await sendMessage(formattedTo, message)
    
    if (!result.success) {
      console.error('[send-kit-whatsapp] Failed:', result.error)
      return res.status(500).json({ 
        error: result.error || 'Failed to send kit via WhatsApp',
        hint: result.error?.includes('not configured') 
          ? 'Please check Twilio configuration in .env.local. See TWILIO_SETUP.md for setup instructions.'
          : 'Please check: 1) Twilio credentials are correct, 2) WhatsApp sandbox is joined, 3) Phone number format is correct',
        kitUrl, // Still return the URL so user can download manually
        whatsappNumber: YOUR_WHATSAPP_NUMBER
      })
    }

    // Try to send the PDF as media if available
    if (filledPdfUrl) {
      try {
        const pdfPath = path.join(process.cwd(), 'public', filledPdfUrl.replace(/^\//, ''))
        if (fs.existsSync(pdfPath)) {
          const pdfUrl = `${baseUrl}${filledPdfUrl}`
          
          // Note: Twilio WhatsApp media requires a publicly accessible URL
          // For now, we'll include it in the message
          // To send actual media, you'd need to upload to a public storage first
          console.log('[send-kit-whatsapp] PDF available at:', pdfUrl)
        }
      } catch (err) {
        console.warn('[send-kit-whatsapp] Could not process PDF:', err)
      }
    }
    
    console.log('[send-kit-whatsapp] Success:', result.sid)
    return res.status(200).json({ 
      ok: true, 
      sid: result.sid,
      message: 'Application kit sent successfully via WhatsApp',
      kitUrl,
      whatsappNumber: YOUR_WHATSAPP_NUMBER
    })
  } catch (err: any) {
    console.error('[send-kit-whatsapp] Error:', err)
    return res.status(500).json({ 
      error: err.message || 'Failed to send kit via WhatsApp',
      details: process.env.NODE_ENV === 'development' ? err.stack : undefined
    })
  }
}

